version: '3.8'

services:
  # Aplicação Go
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - REDIS_URL=redis://redis:6379
      - GIN_MODE=release
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - payment-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "250MB"

  # Redis para cache e armazenamento
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

volumes:
  redis_data:

networks:
  payment-network:
    driver: bridge
